name: badasi
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map_animations: 0.3.0
  flutterflow_ui: ^0.2.0+1
  auto_size_text: 3.0.0
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.17.2
  cloud_firestore_platform_interface: ^6.2.2
  cloud_firestore_web: ^3.12.2
  collection: 1.18.0
  file_picker: ^7.0.2
  firebase_auth: ^4.17.9
  firebase_auth_platform_interface: ^7.2.5
  firebase_auth_web: ^5.11.4
  firebase_core: ^2.30.1
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: ^2.15.0
  firebase_performance: ^0.9.4+4
  firebase_performance_platform_interface: ^0.1.4+32
  firebase_performance_web: ^0.1.6+4
  flutter_animate: ^4.1.1+1
  flutter_cache_manager: ^3.3.0
  flutter_plugin_android_lifecycle: 2.0.9
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: ^13.2.5
  google_fonts: 4.0.3
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.1.23
  google_sign_in_ios: ^5.7.6
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4
  camera: 0.10.5+9
  image_picker: ^1.1.0
  image_picker_android: ^0.8.10
  image_picker_for_web: ^3.0.4
  image_picker_ios: ^0.8.10+1
  image_picker_platform_interface: ^2.10.0
  intl: 0.18.1
  json_path: ^0.7.1
  mime_type: 1.0.0
  page_transition: 2.0.4
  path_provider: ^2.1.3
  path_provider_android: ^2.2.4
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: 2.1.8
  provider: 6.0.4
  rxdart: 0.27.7
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.2.2
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  sign_in_with_apple: ^6.1.0
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0
  stream_transform: 2.1.0
  url_launcher_android: ^6.3.1
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  video_player: ^2.8.6
  video_player_android: ^2.4.14
  video_player_avfoundation: ^2.5.7
  video_player_platform_interface: ^6.2.2
  video_player_web: ^2.3.0
  firebase_storage: ^11.7.4
  firebase_ui_auth: ^1.7.0
  built_collection: 5.1.1
  built_value: 8.4.0
  data_table_2: 2.3.10
  dio: ^4.0.6
  equatable: 2.0.3
  file_picker_cross: ^4.6.0
  firebase_storage_platform_interface: 4.1.25
  firebase_storage_web: 3.3.17
  geo_firestore_flutter: ^0.1.6
  geocode: ^1.0.2
  google_maps: 6.2.0
  google_maps_flutter: 2.1.8
  google_maps_flutter_platform_interface: 2.2.1
  google_maps_flutter_web: 0.4.0+1
  image_downloader: ^0.31.0
  image_picker_web: ^3.0.0+1
  json_serializable: 6.3.1
  mask_text_input_formatter: 2.4.0
  signature: 5.1.0
  timeago: 3.2.2
  url_launcher: 6.1.5

dev_dependencies:
  flutter_lints: ^3.0.2
  lints: 3.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
