// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1g7C9l5ItLdZuJPScgPVk5IZoImnvYEk',
    appId: '1:119698091521:web:2f3a6e9d56c06a17f01a00',
    messagingSenderId: '119698091521',
    projectId: 'badasi-2a92e',
    authDomain: 'badasi-2a92e.firebaseapp.com',
    storageBucket: 'badasi-2a92e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLduNv4Hhiz6NHSYNkUyJi6ZQ61Z1Aig',
    appId: '1:119698091521:android:0fa7990640f024e0f01a00',
    messagingSenderId: '119698091521',
    projectId: 'badasi-2a92e',
    storageBucket: 'badasi-2a92e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjKAmg6pFIF60_2cumOOZ8zStuw9DShW0',
    appId: '1:119698091521:ios:9b7ef698efb3ca2af01a00',
    messagingSenderId: '119698091521',
    projectId: 'badasi-2a92e',
    storageBucket: 'badasi-2a92e.appspot.com',
    iosBundleId: 'com.example.badasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjKAmg6pFIF60_2cumOOZ8zStuw9DShW0',
    appId: '1:119698091521:ios:9b7ef698efb3ca2af01a00',
    messagingSenderId: '119698091521',
    projectId: 'badasi-2a92e',
    storageBucket: 'badasi-2a92e.appspot.com',
    iosBundleId: 'com.example.badasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1g7C9l5ItLdZuJPScgPVk5IZoImnvYEk',
    appId: '1:119698091521:web:e234d1578ab7e0f3f01a00',
    messagingSenderId: '119698091521',
    projectId: 'badasi-2a92e',
    authDomain: 'badasi-2a92e.firebaseapp.com',
    storageBucket: 'badasi-2a92e.appspot.com',
  );

}